disabled_rules:
  - line_length
  - trailing_whitespace
  - unused_optional_binding
  - vertical_whitespace
  
included:
  - Sources
  - Tests
  - VandelayDemo

identifier_name:
  excluded:
    - id
    - vc
